### ISSUE TITLE
Does this not work with juypter-node? I get 'node' could not be spawned, but yet it is within my $PATH

### ISSUE THREAD

**Issue by sebinsua** [willwhitney/hydrogen#10]
I was trying to use [juypter-nodejs](https://github.com/notablemind/jupyter-nodejs).

I started Atom from the command line.

```
'node' could not be spawned.
Is it installed and on your path?
If so please open an issue on the package spawning the process.
```

If I go back to the terminal session:

```
➜  ~  echo $PATH
/Users/sebinsua/.nvm/versions/io.js/v1.8.1/bin:/usr/local/sbin:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/share/python
```

It looks fine to me?

**Comment by willwhitney** [comment]
Just installed `juypter-nodejs` and gave it a try, and it seems to work OK for me.

Two things:
1. Does `which node` in the terminal return the right path to node?
2. Do other kernels (e.g. Python) work?

**Comment by sebinsua** [comment]
It seems to have fixed itself.

**Comment by willwhitney** [comment]
OK, cool. Let me know if you run into any other problems.
