### ISSUE TITLE
Hydrogen doesn't appear to handle unicode function names

### ISSUE THREAD

**Issue by sbromberger** [willwhitney/hydrogen#105]
I've defined the material nonimplication function in Julia as

```
 ⊅(p::Bool, q::Bool) = p & !q
```

Unicode chars are allowed in/as function names in Julia, but trying to execute in Hydrogen gives me a never-ending "processing" graphic (the moving bars). Renaming the function to "foo" resulted in correct behavior.

**Comment by willwhitney** [comment]
Hmm, I know this used to work...

\<does tests throughout git history\>

Looks like unicode names broke in this commit: https://github.com/willwhitney/hydrogen/commit/929777f400beb3a5c552a4cfced6a8d5ea28d472

@n-riesco seems like this is in the signing code (#97) you wrote — mind looking into this?

**Comment by n-riesco** [comment]
@willwhitney I'm having a look at it now.

**Comment by n-riesco** [comment]
@willwhitney In the PR #107 I've hard-coded an "utf-8" encoding. How do you think? Should we get the encoding from atom, instead?

**Comment by sbromberger** [comment]
just wanted to say thanks for looking into this!

**Comment by n-riesco** [comment]
On second thoughts, the encoding is actually determined by the kernel. If the kernel uses utf-8, we should use utf-8.

**Comment by n-riesco** [comment]
@sbromberger Thanks for reporting this issue! (It also affects a package I'm maintaining [JMP](https://github.com/n-riesco/jmp)).

**Comment by sbromberger** [comment]
Dunno if [this](https://groups.google.com/d/msg/julia-users/VW0bWZWQEa4/VJMPO85sAgAJ) helps, but

>  Julia requires source code to be in the UTF-8 encoding of Unicode.

**Comment by willwhitney** [comment]
Using utf-8 everywhere seems to work for all my standard test kernels. Is that PR good to go, or are you doing something more?

**Comment by n-riesco** [comment]
I'm concerned about Windows users (don't they use 'utf16le'?). Right now, I can't test this PR on Windows machine.

**Comment by willwhitney** [comment]
Ugh, that's a good point. Neither can I.

**Comment by n-riesco** [comment]
Before I go offline, let me propose 2 options:

- **conservative option**: disable signing by editing `lib/config-manager.coffee` and setting `key` to "".

- **alternative option**: merge PR #107 (this will fix the issue utf-8 users only)

Once I test the PR on Windows, I can report back my findings here.

**Comment by n-riesco** [comment]
My reading of https://ipython.org/ipython-doc/3/api/generated/IPython.kernel.zmq.session.html#IPython.kernel.zmq.session.Session.serialize is that Jupyter requires the JSON strings to be formatted in `utf8`. If my reading is correct the PR is ready to go.

**Comment by sbromberger** [comment]
Sorry - I can't test windows either.

**Comment by willwhitney** [comment]
I think it'll be fine, and if it's an issue people will let us know. I'm going to go ahead and merge it.

**Comment by n-riesco** [comment]
I've checked and v6.0.2 is working on Windows with the Python, Javascript and Julia kernel

**Comment by willwhitney** [comment]
:+1:
