### ISSUE TITLE
No output of kernel errors

### ISSUE THREAD

**Issue by terraqout** [willwhitney/hydrogen#109]
Hi all. I like hydrogen very much (I'm glad to not using lighttable/juno for julia anymore), thanks for your work.

I have a problem with error handling. For example I've installed ExcelReaders for Julia, it has an internal dependency on python package xlrd. But I can know this only on launching in ipython or julia repl. Hydrogen just show 'waiting' sign and hold. This is a bit frustrating.

Can anyone describe why it wasn't implemented (troubles/drawbacks/etc). Or if this 'just not implemented' I can implement it by myself.

Thanks for any help.

**Comment by terraqout** [comment]
Accidentally I get an error message. But it's again about xlrd, which I installed with pip3 and successfully used in julia repl. This were fixed by installing through pip2, but after that after loading library 'ExcelReaders' kernel doesn't import functions from it.
Is there any way to debug interactions with kernel in more verbose mode and not waiting for zmq answer? I'm a bit disappointed.

I understand this is a bit wider than hydrogen itself. Thanks for any clarifications

**Comment by willwhitney** [comment]
This is just not implemented yet. If you're interested in adding messaging for errors from the kernel on `stderr`, I'd love to see them!

**Comment by terraqout** [comment]
Ok, I'll try to do it.

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/pull/116

**Comment by terraqout** [comment]
@willwhitney Should #116 be merged?
