### ISSUE TITLE
Give output popups a max width and text overflow?

### ISSUE THREAD

**Issue by sherbondy** [willwhitney/hydrogen#11]
Hey pal, when python spews out a really long string, sometimes the output popup exceeds the window width. Can dismiss with clear-results, but maybe the popup should have a maximum width?

![screenshot 2015-05-20 18 12 12](https://cloud.githubusercontent.com/assets/193187/7739332/3f63b6cc-ff1c-11e4-958d-8903d8cffb70.png)

**Comment by willwhitney** [comment]
Whoa, it should already. Not sure why you're getting this. Let me check
into it.

**Comment by sherbondy** [comment]
.bubble-result-container {
        position: relative;
        max-width: 500px;
        max-height: 500px;
        overflow: hidden;
}

should be moved to .bubble-output-container mebbe?

**Comment by willwhitney** [comment]
Yup, just found it. Changing and pushing.
