### ISSUE TITLE
Using non-default version of python with hydrogen

### ISSUE THREAD

**Issue by iprokin** [willwhitney/hydrogen#110]
Taking opportunity, I thank you for your work on amazing hydrogen. 

I have both python2 and 3 jupyter kernels installed. On ArchLinux the default python is python3 with which hydrogen runs nicely. However, I often want to run it with python2 kernel. I didn't find an easy way to select another python kernel in hydrogen. 

None of the things I tried worked:
1) "Language Mapping" {"Python":"python2"} in hydrogen's settings.
2) running atom with "PYTHON=python2.7 atom"
3) running atom with  "alias python='/usr/bin/python2.7'; atom"

It would be nice to have an easy switch between python 2 and 3.

**Comment by willwhitney** [comment]
Yeah, there isn't currently a good way to do this. Eventually I want to implement a more user-friendly way to do this, but

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/pull/138

**Comment by slavaGanzin** [comment]
@iprokin Try changing kernels with Hydrogen/master
