### ISSUE TITLE
Is it possible to run in a virtualenv?

### ISSUE THREAD

**Issue by onyxfish** [willwhitney/hydrogen#114]
Can't find anyway to get it to respect the virtualenv I'm active in when I launch atom.

**Comment by willwhitney** [comment]
Your `PATH ` is picked up from your session by Atom when it's first launched, so I *think* that if you close Atom entirely (all windows), activate your virtualenv, then run Atom from your shell, then it should work. 

You may well have a better understanding of the vagaries of virtualenv than I do, though.

**Comment by onyxfish** [comment]
Hmmm, that doesn't seem to be working for me. I'll take a closer look into debugging it. I'm pretty seriously in love with what you've built here.

**Comment by willwhitney** [comment]
Great to hear! If there's anything that needs improvement, I love pull requests :D

**Comment by onyxfish** [comment]
That is also great to hear. :) I think this one might have been a red herring. I just got it to work after a full terminal restart. It's possible I had the wrong env active. Closing for now. Thanks!
