### ISSUE TITLE
Python 3.4 not supported

### ISSUE THREAD

**Issue by fonnesbeck** [willwhitney/hydrogen#12]
It looks like one of the dependencies (`gyp`) is not compatible with Python >= 3:

    $ apm install hydrogen
    Installing hydrogen to /Users/fonnescj/.atom/packages ✗

    > zmq@2.11.0 install /private/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/apm-install-dir-115420-19773-pwklwc/node_modules/Hydrogen/node_modules/zmq
    > node-gyp rebuild

    gyp ERR! configure error 
    gyp ERR! stack Error: Python executable "python" is v3.4.2, which is not supported by gyp.
    gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
    gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
    gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at maybeClose (child_process.js:766:16)
    gyp ERR! stack     at Socket.<anonymous> (child_process.js:979:11)
    gyp ERR! stack     at Socket.emit (events.js:95:17)
    gyp ERR! stack     at Pipe.close (net.js:466:12)
    gyp ERR! System Darwin 14.4.0
    gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /private/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/apm-install-dir-115420-19773-pwklwc/node_modules/Hydrogen/node_modules/zmq
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    npm ERR! Darwin 14.4.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/fonnescj/.atom/.apm/.apmrc" "--userconfig" "/Users/fonnescj/.atom/.apmrc" "install" "/private/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/d-115420-19773-1756kxc/package.tgz" "--target=0.22.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! zmq@2.11.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the zmq@2.11.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the zmq package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls zmq
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/apm-install-dir-115420-19773-pwklwc/npm-debug.log

**Comment by rgbkrk** [comment]
Hey @fonnesbeck!

That's a known issue with `node-gyp` (https://github.com/TooTallNate/node-gyp/issues/384), which builds native add ons (in this case zmq). I've been pushing to fix this upstream in node-gyp but haven't seen any responses by maintainers (even on issues from 2014).

Can you try installing hydrogen with the command line `apm` tool, setting the PYTHON environment variable?

```
PYTHON=python2.7 apm install hydrogen
```

Technically, the node-gyp instructions tell people to set it via `node-gyp` or `npm` config but with `apm` bundling both `node-gyp` and `npm` I'm not sure how to overwrite it.

**Comment by fonnesbeck** [comment]
I see. That's a deal breaker for me, as I work exclusively in Python 3 these days. Bizarre that they won't update their package.

**Comment by willwhitney** [comment]
@fonnesbeck It will still *run* Python 3, it's only the *installer* for `node-gyp` that needs Python 2.

**Comment by rgbkrk** [comment]
From https://github.com/TooTallNate/node-gyp/issues/193, seems like much of the issue actually comes from `gyp`: https://code.google.com/p/gyp/issues/detail?id=36

**Comment by fonnesbeck** [comment]
@willwhitney I see; I had assumed it was associated with the IPython that gets used by hydrogen. setting the `PYTHON` flag seems to work. Thanks.

**Comment by willwhitney** [comment]
Awesome, glad you're up and running now.

@rgbkrk I'm starting to really wish for a Javascript ZMQ implementation — `gyp` seems to be causing a lot of problems.

**Comment by rgbkrk** [comment]
With new versions of node-gyp, they'll now also check for `python2`. Hurrah!

**Comment by willwhitney** [comment]
Nice!
