### ISSUE TITLE
"Add to watch" command/shortcut

### ISSUE THREAD

**Issue by terraqout** [willwhitney/hydrogen#120]
This is neat function but it isn't declared as command so you always need to use "Add watch" button.

I want to implement add to watch command for atom:
1. Check if selected text is evaluatable(evaluable, able to eval?)/variable
2. Add to watch if 1 is true
3. Show error if not

I think it would be great to add shortcut for that, maybe ctrl-alt-enter. Any ideas?

**Comment by n-riesco** [comment]
`ctrl-alt-enter` would conflict with [this PR](https://github.com/willwhitney/hydrogen/pull/101).

**Comment by terraqout** [comment]
@willwhitney would you merge this if I create PR?

**Comment by willwhitney** [comment]
Yup, this would be a great addition. Probably just create a command with no default shortcut for right now so people can map it however they like.

It's probably not possible to check whether the code is valid in a safe way. The best thing might be to add it unconditionally and let the user see the error in the output of the watch expression just as they usually would.

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/pull/122
