### ISSUE TITLE
Unable to get hydrogen working in atom 1.1.0 with julia 0.4

### ISSUE THREAD

**Issue by JeremyCavanagh** [willwhitney/hydrogen#127]
I have followed the installation instructions very carefully and when I try to use hydrogen I get the following message (this is not the full text but the important part):

'/usr/local/Cellar/julia/0.3.6_1/bin/julia could not be spawned'

However, the only version of julia on my system is 0.4.0

I am running on Mac OS X 10.9.5

**Comment by willwhitney** [comment]
The Julia kernel has had some issues in the past with leaving kernelspecs around that are no longer correct. If you check in `~/.ipython/kernels/` and `~/Library/Jupyter/kernels` and `/usr/local/share/jupyter/kernels` (good lord, Jupyter needs to figure out where they want to store these) I bet you'll find an old `julia 0.3` directory that tells Jupyter to launch an old version of Julia. Just delete that directory and everything should work.

Let me know if that doesn't fix it and I'll reopen.

**Comment by JeremyCavanagh** [comment]
Hi Will,
 you are a genius old references to 0.3 kernels found in your first two suggestions nothing in the third. Now no errors, just need to spend some time to see if everything is working properly. I'm new to julia and especially atom so my explorations are just beginning.

Many thanks for your help

**Comment by willwhitney** [comment]
Awesome, glad that worked!
