### ISSUE TITLE
Running hydrogen on mac os x with anaconda3

### ISSUE THREAD

**Issue by fr4ggle** [willwhitney/hydrogen#137]
Hi,

I hope this is the right place to look for help. If not so forgive me since I am new to this but I want to start learning python for usage with the RaspberryPI. I read that it makes more sense to start with python3 rather than python2. So I installed Anaconda3 on mac os x and want to use the atom editor with the hydrogen package to start my adventure.
I understand the requirement that I need python2.x to run hydrogen, but I want to use python3.x for learning programming. I thought I might get around this issue by creating an environment with anaconda using python2.x,

`conda create --name python2 python=2`

and then switch to it by

`source activate python2`

however, while this creates and switches to the desired environment, atom and hydrogen still seem to try use python3 when I start atom in the environment python2 from the terminal. Does anyone here know how to correctly set up what I described above?

Thanks a lot in advance!

**Comment by terraqout** [comment]
@fr4ggle I think this answer should help: http://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook

Hydrogen is just an GUI interacting with jupyter(ipython) kernels, so if you didn't find answer at stackoverflow better consult with that community. If someone, wouldn't answer here. I'm linux user, so I never used anaconda for that — it just works.

Have a good luck on your python way!
