### ISSUE TITLE
Issue with imports

### ISSUE THREAD

**Issue by terraqout** [willwhitney/hydrogen#139]
Relative import paths cant be used in file placed not in project root folder.
This is a bit frustrating ­— we even can't use hydrogen to develop hydrogen.

So kernel path should be changed before any command executed for a new file. Is there any way to change working directory in jupyter "meta" kernel? Maybe implement some zmq command that change config?

@n-riesco, Nicolas I ask you for help again

**Comment by n-riesco** [comment]
@terraqout  I'm not sure what this issue is about. Isn't the kernel's working directory set [here](https://github.com/willwhitney/hydrogen/blob/master/lib/kernel.coffee#L53)?

**Comment by n-riesco** [comment]
I've used the files below and relative imports currently seem to work in IJavascript. Could you give an example of "Relative import paths cant be used in file placed not in project root folder"?

[test/test.js]
```javascript
var msg = require("../msg.js");
console.log(msg);
```

[msg.js]
```javascript
module.exports = "Hello, World!";
```

**Comment by terraqout** [comment]
@n-riesco Sorry for being unclear. I wasn't right in issue description.

I didn't try to require something from upper folder. But if you would move test.js to the same folder as msg.js and change code to:
```
var msg = require("./msg.js");
console.log(msg);
```

It raise ```Error: Cannot find module './msg'```

Same is happening if you'll try ``` require('./test/test.js') ``` from msg.js.

So './' notation isn't working in ijavascript.

**Comment by n-riesco** [comment]
It works for me.

Could it be that the issue you see is caused by kernel reuse?

Note that Hydrogen uses the same IJavascript kernel for all the Javascript files. The kernel working folder will be whatever was the folder of the first Javascript file on which Hydrogen was invoked.

**Comment by n-riesco** [comment]
There is an open issue https://github.com/willwhitney/hydrogen/issues/84 requesting a way to select a kernel for different versions of a language (Python 2/3, Julia 0.3/4,...).

One way to address the issue here and the others is to have a dialog that lets you choose not only the language version, but also whether you want to spin a new kernel, or even what you want the working folder to be. This would allow to run different kernels for different projects in the same atom session.

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/pull/138 Here is my PR that fix #84, besides. And this isn't related.

**But**, I want to use single kernel to work on different files. I implement this by sending ```'%cd ' + __dirname__``` on file change.  It works for python kernel, because it implements %cd "magic". 
 I understand there is no need in magics at all. But this can be universal interface, because implementing in hydrogen kernel specific code for changing working directory isn't ok too. 

p.s. One of obvious issues with this approach is variable scope clash. But "I will think about this tomorrow"

**Comment by n-riesco** [comment]
@terraqout It would break Hydrogen for any script that sets the current working directory, for example:

```javascript
var fs = require("fs");
process.chdir(process.env.HOME);
fs.writeFileSync("test.txt", "Hello, World!");
```

**Comment by terraqout** [comment]
this isn't perfect decision and it have drawbacks. But monkeypatching require isn't good too, as any other "magic".

If you have any thoughts about - I'm open to discuss. You know a lot more about kernels and I'm just pushing this issue, which is critical for me

**Comment by n-riesco** [comment]
Just to be clear, I consider both options (magic or *-patching) bad because they break Hydrogen for programs that change the working directory.

Let's consider the pros and cons of the options so far:

1. %magic:
    - :ok: It makes relative imports work for languages where relative paths are relative to the file.
    - :no_entry_sign: It can break relative imports for languages where the relative import is relative to the project root.
    - :no_entry_sign: It breaks kernels that do not provide the %cd magic (either because they don't provide magics or because the %cd magic is not appropriate for that kernel).
    - :no_entry_sign: It breaks program files that need to change the working directory (simple example provided [here](https://github.com/willwhitney/hydrogen/issues/139#issuecomment-161107924)).
    - :no_entry_sign: User must remember to restart the kernel every time they want to use Hydrogen on a new project.

2. *-patching:
    - :ok: It makes relative imports work for languages where relative paths are relative to the file.
    - :no_entry_sign: It can break relative imports for languages where the relative import is relative to the project root.
    - :no_entry_sign: It requires Hydrogen to know how to change the working directory for every kernel.
    - :no_entry_sign: It breaks program files that need to change the working directory (simple example provided [here](https://github.com/willwhitney/hydrogen/issues/139#issuecomment-161107924)).
    - :no_entry_sign: User must remember to restart the kernel every time they want to use Hydrogen on a new project.

3. [kernel dialog](https://github.com/willwhitney/hydrogen/issues/139#issuecomment-161020208):
    - :ok: It makes relative imports work for languages where relative paths are relative to the file.
    - :ok: It makes relative imports work for languages where the relative import is relative to the project root.
    - :ok: It doesn't require Hydrogen to know how to change the working directory for every kernel.
    - :ok: It doesn't break program files that need to change the working directory (simple example provided [here](https://github.com/willwhitney/hydrogen/issues/139#issuecomment-161107924)).
    - :ok: Multiple projects can be edited simultaneously without restarting the kernel.

**Comment by terraqout** [comment]
>One way to address the issue here and the others is to have a dialog that lets you choose not only the language version, but also whether you want to spin a new kernel, or even what you want the working folder to be.

If go to new file and launch ```Hydrogen: restart kernel``` command you'll get new kernel with new cwd.

> This would allow to run different kernels for different projects in the same atom session.
What the case for? it's look like really rare scenario: using atom for different projects at one time.
:ok: Multiple projects can be edited simultaneously without restarting the kernel.
You definitely should restart or use another kernel on another project — there is no any scope management mechanism (but it would be great to have one).

What I want to achieve is transparent work in one project. Ideally I want to forget about kernels and just work on my project. 

:no_entry_sign: It makes relative imports work for languages where relative paths are relative to the file.
Now it can't import file from the same folder. I can't work on Hydrogen using Hydrogen itself, that's ridiculous.

:ok: It doesn't require Hydrogen to know how to change the working directory for every kernel.
As I said before this can and should be moved to each kernel configuration

Clearly, I didn't see any elegant way to fix it. Except of implementing scopes in proto jupyter kernel.

**Comment by n-riesco** [comment]
I feel the discussion is digressing. Let me try to refocus on the issue you want to solve.

As I said [here](https://github.com/willwhitney/hydrogen/issues/139#issuecomment-160892060) and [here](https://github.com/willwhitney/hydrogen/issues/139#issuecomment-161012173), relative imports work now provided the user is careful enough to start (or restart) the kernel at the project's root folder.

Please, could you give an example of how it isn't possible to develop Hydrogen in Hydrogen?

**Comment by terraqout** [comment]
https://github.com/willwhitney/hydrogen/blob/master/lib/kernel.coffee#L9 just try to execute at this line

```Error
Cannot find module './watch-sidebar'
Error: Cannot find module './watch-sidebar'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:289:25)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at evalmachine.<anonymous>:3:16
at Object.exports.runInThisContext (vm.js:54:17)
at run ([eval]:192:19)
at onMessage ([eval]:63:41)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
```

If I change
```StatusView = require './status-view'```
to
```StatusView = require './status-view*.coffee*'```

I get
```
SyntaxError: Unexpected string
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:404:25)
at Object.Module._extensions..js (module.js:432:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:313:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at evalmachine.<anonymous>:3:14
at Object.exports.runInThisContext (vm.js:54:17)
at run ([eval]:192:19)SyntaxError
Unexpected string
```

**Comment by n-riesco** [comment]
OK, I see. The issue is actually caused by the CoffeeScript kernel (`jp-coffeescript`).

The way `jp-coffeescript` works is by transpiling coffeescript into javascript that can be run in a Node.js session. The `require` function in Node.js doesn't look for files with the `.coffee` extension, and even if it did, it wouldn't understand the coffeescript code.

I've opened an issue in the `jp-coffeescript` repository; see https://github.com/n-riesco/jp-coffeescript/issues/5

**Comment by terraqout** [comment]
Looks I failed a lot with this issue.

@n-riesco Thanks for your work

**Comment by n-riesco** [comment]
@terraqout Also thanks from me for your work. Thanks to this issue, now:
- Hydrogen can choose between Python 2 and Python 3
- `require` works in `jp-coffeescript`

**Comment by terraqout** [comment]
@n-riesco It needs to be approved from @willwhitney and merged before
