### ISSUE TITLE
raw input causes error

### ISSUE THREAD

**Issue by hugeme** [willwhitney/hydrogen#146]
Hi,

I tried the same command in `Jupyter Notebook`without any issues. Do I miss something somewhere?

`aName = input('Please enter your name: ')`

causes: 

    ---------------------------------------------------------------------------
    StdinNotImplementedError                  Traceback (most recent call last)
    <ipython-input-6-4df7c615c3df> in <module>()
    ----> 1 aName = input('Please enter your name: ')
    /usr/local/lib/python2.7/site-packages/ipykernel/ipkernel.pyc in <lambda>(prompt)
        139             self._sys_eval_input = builtin_mod.input
        140             builtin_mod.raw_input = self.raw_input
    --> 141             builtin_mod.input = lambda prompt='': eval(self.raw_input(prompt))
        142         self._save_getpass = getpass.getpass
        143         getpass.getpass = self.getpass
     /usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.pyc in raw_input(self, prompt)
        670         if not self._allow_stdin:
        671             raise StdinNotImplementedError(
    --> 672                 "raw_input was called, but this frontend does not support input requests."
        673             )
        674         return self._input_request(prompt,
    StdinNotImplementedError: raw_input was called, but this frontend does not support input          requests.StdinNotImplementedError
    raw_input was called, but this frontend does not support input requests.

**Comment by terraqout** [comment]
This is kernel specific issue. We didn't support %magics and other "ipython only" stuff. 
So what do you want to achieve? Prompt box?
