### ISSUE TITLE
ijavascript kernel issues

### ISSUE THREAD

**Issue by joshthecoder** [willwhitney/hydrogen#15]
Anyone manage to get the ijavascript kernel working?
When I try to run JavaScript code in hydrogen is just hangs there waiting for results.

**Comment by willwhitney** [comment]
Just tracked it down — the IJavascript kernel has an issue with parsing messages when HMAC signing is turned off. Getting a pull request on that kernel ready now.

**Comment by willwhitney** [comment]
I've got a PR open with them at https://github.com/n-riesco/ijavascript/pull/29

**Comment by willwhitney** [comment]
This PR has been merged! Update to the latest version and you should be good to go.
