### ISSUE TITLE
No kernel for language shell script found

### ISSUE THREAD

**Issue by nmiculinic** [willwhitney/hydrogen#151]
I've installed bash [kernel](https://github.com/takluyver/bash_kernel) for Jupyter, tested it in jupyter notebook and it works like a charm.

Next I've tried making .sh script in atom and using hydrogen to evaluate line by line, however I get the title error with following message:
```
Check that the language for this file is set in Atom and that you have a Jupyter kernel installed for it.
```

There's probably some wiring issue somewhere since atom calls language ```shell script``` and it's called ```bash``` in jupyter 

(at least I think so from inspecting ```~/.local/share/jupyter/kernels/bash/kernel.json``` :  
```
{"argv": ["/home/nmiculinic/anaconda3/bin/python", "-m", "bash_kernel", "-f", "{connection_file}"], "codemirror_mode": "shell", "display_name": "Bash", "env": {"PS1": "$"}, "language": "bash"}
```
)

I'm not exactly sure where in atom/hydrogen should I fix this wiring to properly use bash kernel?

**Comment by willwhitney** [comment]
You can add mappings like this to the package settings for Hydrogen. It takes a JSON mapping from the nonstandard name (the grammar Atom is using) to the kernel language.

**Comment by nmiculinic** [comment]
Thank you!
