### ISSUE TITLE
MacPorts support

### ISSUE THREAD

**Issue by ksze** [willwhitney/hydrogen#18]
I'm a MacPorts guy. Is it possible to remove the hard dependency on the Homebrew pkg-config and zmq? Or is that out of your control?

**Comment by willwhitney** [comment]
As long as you've got ZeroMQ and pkg-config, it shouldn't matter where they came from. Homebrew is currently serving up pkg-config@0.28 and zmq@4.0.5.

**Comment by ksze** [comment]
That's strange. Right now the installation of Hydrogen still fails with a `/bin/sh: pkg-config: command not found` when it tries to use pkg-config, just like @speg mentions here: https://github.com/willwhitney/hydrogen/issues/13#issuecomment-104299794

**Comment by willwhitney** [comment]
Does running `pkg-config --version` in the terminal give you 0.28?

**Comment by ksze** [comment]
Yes, it does give me 0.28.

**Comment by willwhitney** [comment]
Shit, sorry, I just realized I missed half of your previous comment. That's pretty mysterious to me.

If your main interest is just getting this running, I have to recommend Homebrew. It's what most people are using and it seems to work fine. If you're interested in getting this working with MacPorts, I'd love the help. Having to build `zmq` using [`node-gyp`](https://github.com/TooTallNate/node-gyp) seems to be the source of 80% of the problems people have with installing.

**Comment by jzthree** [comment]
@ksze  did you launch atom by typing atom <location> command? I happened to have the same error when I installed hydrogen on my mac and realized that it couldn't find pkg-config if atom is not launched this way.

**Comment by willwhitney** [comment]
@jzthree +1 — just ran into someone who had this issue while trying to update the package.

**Comment by rgbkrk** [comment]
The other alternative is to run `apm install hydrogen` from the command line (to get your full path suite).

**Comment by ksze** [comment]
@rgbkrk Installing using the `apm install hydrogen` works. Thanks!
