### ISSUE TITLE
Integrate with autocomplete plus

### ISSUE THREAD

**Issue by rgbkrk** [willwhitney/hydrogen#2]
The autocomplete feature of the running kernel is quite beautiful. Now that [autocomplete plus is part of Atom](http://blog.atom.io/2015/05/15/new-autocomplete.html), it would be nice to somehow merge the autocomplete suggestions so you get the best of the static analysis and dynamic running kernel.

**Comment by willwhitney** [comment]
This is already acting as an autocomplete+ provider, and does not exclude the suggestions from other providers.

**Comment by rgbkrk** [comment]
Nevermind me, I thought it was overriding the autocomplete+ look and feel with the jupyter output.
