### ISSUE TITLE
Hydrogen doesn't seem to detect my iPython installation

### ISSUE THREAD

**Issue by acpcalin** [willwhitney/hydrogen#21]
I am running an Arch Linux System and I have installed iPython using the default package manager, however Hydrogen doesn't seem to find my installation. I don't understand how the whole "kernel" thing works with iPython, I just want the fancy functionality of Hydrogen. I'm sorry I posted this here but I didn't know where else to put it.
![image](https://cloud.githubusercontent.com/assets/9417983/7780570/1cbd754e-00e9-11e5-8b4f-76828572978b.png)

As you can see, there's no python kernel: <kernel> in the bottom left.

**Comment by rgbkrk** [comment]
This may be related to other path and kernel search issues, which might be addressed in #19. I'm assuming arch uses the XDG directories and env variables?

**Comment by willwhitney** [comment]
This is a fine place to ask!

Hydrogen doesn't start a kernel until you run something, so if you haven't done a "Hydrogen:run" command yet, the kernel won't show up.

Otherwise, did you start Atom from the command line? If not, it can't see your $PATH.

Let me know if neither of those solves it and we'll try to figure out the problem.

**Comment by acpcalin** [comment]
willwhiteney, when I run hydrogen it shows the following near the line of code, however nothing happens:
![image](https://cloud.githubusercontent.com/assets/9417983/7782742/a6cf630a-012f-11e5-81f7-250245ce0b4d.png)

rgbkrk, I'll check out that link after I document myself what arch uses.

**Comment by rgbkrk** [comment]
Jupyter is just the next release. Which version of IPython are you on?

**Comment by acpcalin** [comment]
Python 3.4.3 and IPython 3.1.0. Although I also have Python 2.7.9 and its respective IPython (3.1.0) installed.

**Comment by rgbkrk** [comment]
Can you run 

```python
from IPython.utils.path import get_ipython_dir; get_ipython_dir()
```

in a python or IPython terminal?

**Comment by acpcalin** [comment]
Sure, sorry for the delay:
    `Out[1]: '/home/calin/.ipython'`
That's what I get.

**Comment by willwhitney** [comment]
@acpcalin I log a bunch of stuff out to the console to help debug this sort of thing — mind updating to the latest version, then opening the dev console (View -> Developer -> Toggle Developer Tools) and trying to run something? It should spit out `launching kernel:` followed by the command and arguments it's using to try to start the kernel, along with any errors.

**Comment by acpcalin** [comment]
```python
launching kernel: ipython ["kernel", "--no-secure", "--hb=47608", "--control=50748", "--shell=35255", "--stdin=41349", "--iopub=46541", "--colors=NoColor"]
```

**Comment by willwhitney** [comment]
If you leave it waiting for a response, then run that command in your terminal (`ipython kernel --no-secure --hb=47608 --control=50748 --shell=35255 --stdin=41349 --iopub=46541 --colors=NoColor`) then it should resolve the result, yes?

Does `process.env.PATH` looks right in the Atom console? It could be that Atom is somehow failing to get the PATH properly.

**Comment by acpcalin** [comment]
where do I find this entry in the Atom console?

**Comment by willwhitney** [comment]
Ooh, that's probably the culprit. Investigating...

**Comment by acpcalin** [comment]
No, sorry. Actually the output is 
```
"/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:~/.atom"
```

I didn't know that command was case-sensitive, I am sorry.

**Comment by willwhitney** [comment]
OK, cool. Now try running `cp.spawnSync('ipython', ['--version']).stdout.toString()` in the Atom console.

**Comment by acpcalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9417983/7789179/a967e146-0260-11e5-8a3a-be5e9bef2bea.png)

**Comment by willwhitney** [comment]
Whoops. Run `cp = require('child_process')` first, sorry about that.

**Comment by acpcalin** [comment]
No problem. 
![image](https://cloud.githubusercontent.com/assets/9417983/7789185/dfa13f00-0260-11e5-8764-7625f43f278f.png)

**Comment by willwhitney** [comment]
OK, so it's definitely able to find your ipython install.

Try running something with Hydrogen, then while it's failing to give you a result, flip over to the terminal and running `ipython kernel --no-secure --hb=47608 --control=50748 --shell=35255 --stdin=41349 --iopub=46541 --colors=NoColor` (and substitute for the ports that Hydrogen has printed in the "launching kernel" message if they're different).

**Comment by acpcalin** [comment]
Ok, this is weird. I didn't run those commands yet, because the problem seems to be fixed now. I don't know why or how, however. I'll tell you step by step what I have done: First I tried to run Atom as root (`sudo atom`) and noticed that the root profile didn't have Hydrogen installed, even though I installed it inAtom on my normal, non-root, account. Then I tried installing Hydrogen as root. This way it tried to install somewhere in the .root folder so that it would show up when I ran Atom with sudo. It failed with an error code(I closed the window, unfortunately).
Now, however, Hydrogen works on my normal profile. After I select Hydrogen:Run, it takes 1 second until it detects the IPython kernel and then it works just as expected. 
![image](https://cloud.githubusercontent.com/assets/9417983/7789240/71676f8a-0262-11e5-8359-988a51b21c63.png)

**Comment by willwhitney** [comment]
Yup, that's bizarre. I'm glad it's working for you now!

Is it possible that this was just a side effect of restarting Atom?

**Comment by acpcalin** [comment]
I don't really know, maybe. Thanks for the help!

**Comment by acpcalin** [comment]
I just realized, sometimes Hydrogen finds the kernel, sometimes it doesn't. Closing and opening Atom several times and trying to run Hydrogen after each time is the solution. I don't know why, but I'm glad it works now.

**Comment by willwhitney** [comment]
That's very weird. I wouldn't be surprised if it's an issue of the kernel
failing to get started rather than it not being found.

I just published a version with a little more logging of what the kernel
process is doing, so if it keeps being unreliable, you can check out the
new logs and maybe see what's happening.

**Comment by hugeme** [comment]
May I jump in? Having the same issue, that the kernel is not displayed in the bottom left.

**Comment by terraqout** [comment]
```ln -s /usr/local/share/kernels/python2 ~/.ipython/kernels```
Try this. 

It's a bug fixed here: https://github.com/willwhitney/hydrogen/pull/144
If hydrogen can't to interpret all folders as kernels it fails and return no kernels at all.

**Comment by hugeme** [comment]
@terraqout Thank you for that suggestion. However, I dont have that path `/usr/local/share/kernels/python2`. 

`sudo find / -type d -name 'kernels' ` gives back:
`Users/me/Library/Jupyter/kernels`
`/usr/local/lib/python2.7/site-packages/notebook/services/kernels`
`/usr/local/lib/python2.7/site-packages/notebook/static/services/kernels`
`/Users/me/Library/Jupyter/kernels`
`/usr/local/lib/python2.7/site-packages/notebook/services/kernels`
`/usr/local/lib/python2.7/site-packages/notebook/static/services/kernels`

and none of them contains `python2.` 
Additionally, I use `brew` `/usr/local/Cellar/python/2.7.11/share/python` 

Not sure whether that matters but `hydrogen` is not listed in installed packages within `atom` as well as in .atom/.apm/. But I can still `Hydrogen:run`. Additionally `sudo atom` and `Hydrogen:run` results  [#135](https://github.com/willwhitney/hydrogen/issues/135).

**Comment by terraqout** [comment]
@hugeme Generally I don't know how to install kernels properly on MacOS. So you can look here: 
But as I remember this should work: ```sudo python3 -m IPython kernelspec install-self```.

Please copy output of ```jupyter --paths``` for investigation purposes.

You have python kernel in a list because it was shamelessly hardcoded. So hydrogen may not founding it.

----
To fix #135 you should reinstall hydrogen as a regular user and then ```apm rebuild```

**Comment by terraqout** [comment]
@hugeme And besides, I would appreciate if you experiment with https://github.com/willwhitney/hydrogen/pull/144 on the same setup before any "fixing".

```
cd to/your/.atom/packages
rm Hydrogen -rf
git clone git@github.com:willwhitney/hydrogen.git
cd hydrogen
git checkout kernelManagerImpove
apm rebuild
```

If it would fix your issue, I'll merge it in master.

**Comment by hugeme** [comment]
@terraqout #135 seems to be fixed, I'll get again In the right upper corner a blue box with "Scopes at Cursor"
Next:
The `jupyter --paths` are:
`onfig:
    /Users/me/.jupyter
    /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/me/Library/Jupyter
    /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/me/Library/Jupyter/runtime`

Next:
I run what you have suggested which ends with `apm rebuild` without any errors. Restarting `atom` from command line and `Hydrogen:run`results in a new error. Red box similar to the #135 however with `cannot find module zmq`

**Comment by terraqout** [comment]
That's ok — Red box is kernel error, so install zmq as described here: https://github.com/willwhitney/hydrogen#os-x  and retry.

**Comment by hugeme** [comment]
Do you mean that part?:
`pkg-config: brew install pkg-config
ZeroMQ: brew install zeromq`
Both are already brewed/installed

**Comment by terraqout** [comment]
Jupyter needs zmq for python2, you may have zmq for third.

Try ```pip2 install zmq``` or if your python defaults to second version just  ```pip install zmq```.

**Comment by hugeme** [comment]
reinstall `zmq` via `pip` but with the same error

**Comment by terraqout** [comment]
So your kernel isn't in default folder

what is placed here: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/etc/jupyter

?

**Comment by hugeme** [comment]
That ends here:

`/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7`

Headers		Resources	include
Python		bin		lib

**Comment by terraqout** [comment]
Looks like you have the same issue https://github.com/willwhitney/hydrogen/issues/142

**Comment by terraqout** [comment]
Drop your zeromq and try to install other way. It should help :)

**Comment by hugeme** [comment]
so I uninstalled `zeromq`but not fully understand what you meant by `other way`. Are your referring to #142 ? I couldnt see any explicit instructions there..

**Comment by hugeme** [comment]
Thank you! Thats it! "other way around" solved it!

**Comment by terraqout** [comment]
@hugeme Can you explain your experience. So we can add this to readme.md?

**Comment by ssahaxd** [comment]
# Solution
---
Just make sure, Python is installed for all users and it is added to the environment variables.
![ss](https://user-images.githubusercontent.com/11327529/29982063-cfa6d654-8f6d-11e7-8c8f-c434300617cb.jpg)
I was also facing the same problem, after adding it to the environment all my problems are solved.

**Comment by BenRussert** [comment]
@ssahaxd are you interested in making a contribution about this to our [docs installation page](https://github.com/nteract/hydrogen/blob/master/docs/Installation.md)? The environment variables issue comes up frequently from windows users.

**Comment by ssahaxd** [comment]
@BenRussert of course, I would like to contribute.
where the detailed article I should post?
Troubleshooting page looks a great spot.

**Comment by BenRussert** [comment]
That's great!

> Troubleshooting page looks a great spot.

I agree, especially if you want to go into detail.

**Comment by ssahaxd** [comment]
@BenRussert 
added and created a pull request.

**Comment by BenRussert** [comment]
@ssahaxd thanks again!

**Comment by rgbkrk** [comment]
That is so crazy that the Windows installer doesn't include Python on the path by default. O___O
