### ISSUE TITLE
Logo is exactly the same as ionic

### ISSUE THREAD

**Issue by stenmuchow** [willwhitney/hydrogen#23]
FYI.

**Comment by willwhitney** [comment]
Haha yeah, somebody on HN pointed it out. Changing it is on the to do list
:)

**Comment by willwhitney** [comment]
OK, five minutes in Sketch and now it's not _exactly_ the same as Iconic. I guess it shouldn't have been surprising that someone had a logo like that already.

Closed by 0de81518083b04a3cbdf75565fec7e0cb077aa18
