### ISSUE TITLE
investigate using fix-path

### ISSUE THREAD

**Issue by willwhitney** [willwhitney/hydrogen#28]
[`fix-path`](https://github.com/sindresorhus/fix-path) may be able to make the path work when Atom is launched as an app. It won't fix problems with `node-gyp` during installation or update, though.

**Comment by rgbkrk** [comment]
The one thing I'd want to be sure of is that fix-path won't override what's currently in the path (if someone is being explicit).

**Comment by willwhitney** [comment]
Per my comment in #34, I think this is going to lead to bugs down the road and should be corrected in Atom instead.
