### ISSUE TITLE
Does not seem to work with Jupyter's R kernel 

### ISSUE THREAD

**Issue by trcook** [willwhitney/hydrogen#29]
I love the idea of this plugin. 
I can't seem to get hydrogen to run on Jupyter's R kernel though (https://github.com/IRkernel/IRkernel)
When I enter a command and then try to evaluate it, i just get the 'working' animation, and it runs forever. 

I realize that i'm asking about a (somewhat) underdeveloped kernel and that the problem may very well may not be on hydrogen's end. But I really don't have any way to know if it is hydrogen or something else since hydrogen is not reporting much in the way of errors or what it is doing at a given moment. Is there any way to get debugging information out of hydrogen? Outside of the sort of trial and error i described above, is there any way to figure out if hydrogen is actually successfully connecting with the intended kernel?

on my end: 
I'm using the latest version of hydrogen (0.3.9), version 3.0.0 of ipython (jupyter), and the .3 version of the IRkernel. 
I can also get the r kernel to work normally through a jupyter notebook or console. 
I tested and was able to get hydrogen to work with python in atom.io

**Comment by willwhitney** [comment]
IRkernel is working for me after a pull request (https://github.com/IRkernel/IRkernel/pull/139) I wrote for it — I'm definitely interested in making Hydrogen work properly with R. If you install IRkernel from master it should work. Let me know if that's not the case and I'll reopen this.

As a side note, we should really be doing a better job of showing error messages. It's sometimes hard to figure out whether messages coming from the kernel are significant or not (for example, the Julia kernel writes lots of warnings to `stderr` while installing packages), but we need to expose them somehow. Just opened #30 to address this.

**Comment by trcook** [comment]
Cool. I'll checkout the new version of IRkernel. I agree, I think the bigger issue is surfacing debugging messages from hydrogen. I imagine that this would be alot easier if atom a proper console pane like sublime. 

An easy short term solution might be to have a tool-tip style window show up when hovering over the 'working' bubbles that reports hydrogen's status (i.e. sending to kernel, waiting for response, parsing response, etc.). It's just an idea. 

I'll report back to confirm whether the IR kernel fix works.

**Comment by trcook** [comment]
it worked! 
Be advised, though, to get this to work properly, users need to install from the github repo directly (using devtools). This is what the IRkernel devs list under installing the development version. This caveat will eventually go away, i imagine, with the next release from that team. 

Thanks again for this plugin it looks super promising.

**Comment by yang0733** [comment]
i can't seem to get this code running. it's giving me an warning message and i can't fire up ir through the terminal. 

> IRkernel::installspec()
jupyter: 'kernelspec' is not a Jupyter command
Warning message:
running command '"jupyter" kernelspec install --replace --name ir --user C:\Users\i50077\AppData\Local\Temp\RtmpoRwj3q\file187865501005/kernelspec' had status 1

**Comment by willwhitney** [comment]
This may be a Jupyter version issue?

I don't know much about how IRkernel in particular works — you'll have more luck filing an issue over here: https://github.com/IRkernel/IRkernel
