### ISSUE TITLE
user-visible error messages

### ISSUE THREAD

**Issue by willwhitney** [willwhitney/hydrogen#30]
Currently messages from `stdout` and `stderr` of the kernels are logged to the console, but really we should be putting them somewhere with more visibility for the user. 

Maybe a status bar error indicator that opens an editor with all the messages?

**Comment by terraqout** [comment]
@willwhitney Close this?
I'll add log level soon, besides.

**Comment by willwhitney** [comment]
:heavy_check_mark:
