### ISSUE TITLE
Results appearance

### ISSUE THREAD

**Issue by averrin** [willwhitney/hydrogen#32]
![hydrogen_colors](https://cloud.githubusercontent.com/assets/426007/7800265/838ce4ce-031b-11e5-9455-80ce648a9e51.png)

UI Theme: OneDark
Syntax Theme: Watson
Font: Fantasque Sans Mono (with default font there is not even rect char)

**Comment by averrin** [comment]
Updating atom to 0.201 helps.

**Comment by willwhitney** [comment]
Glad this resolved itself!

I'm using the unicode check mark, and I should switch it to the octicon. Opened #33 to address this.
