### ISSUE TITLE
Variable Panel

### ISSUE THREAD

**Issue by TKCen** [willwhitney/hydrogen#41]
A panel with a searchbox which displays all currently defined objects of the kernel would be useful. 
The %who and %whos magics already provide a good interface for this, I don't know if they are available for other kernels aside from the python one.

**Comment by willwhitney** [comment]
I think #25 is the closest we can come to this in a cross-language way. Most kernels don't seem to support magics much.

I completely agree that automatically pulling all the variables out of the kernel would be a lot better, but it will require kernel support and changes to the API.
