### ISSUE TITLE
Tested with node.js

### ISSUE THREAD

**Issue by ricardofbarros** [willwhitney/hydrogen#45]
Everything seems alright on OSX.

![screen shot 2015-05-27 at 15 17 20](https://cloud.githubusercontent.com/assets/6867996/7838220/a98c3cb0-0483-11e5-9de2-c86978843c53.png)

I just installed the [node.js/javascript kernel](https://github.com/notablemind/jupyter-nodejs) restarted atom and rock on! This is awesome!

We could add node.js to the front page as well.

**Comment by willwhitney** [comment]
Nice, glad it's working for you! I've added a few more tested kernels to the readme.
