### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by X-G** [willwhitney/hydrogen#47]
This is an amazing package.  But when I try to use it. It display like this. 
Some particular combination of UI theme and syntax theme may cause the backgroud and the font using the same color.
I'm using `One Light` + `Chester Atom`
![a](https://cloud.githubusercontent.com/assets/6829403/7879986/a28a2b7a-05f5-11e5-9b65-92d1f5433c90.png)

I have tried other combinations, basically the 'light UI' works well with 'light syntax', and 'dark UI' works well with 'dark syntax'.

**Comment by willwhitney** [comment]
@X-G Just shipped an update to try address this. Let me know if there's any problem!

I was accidentally basing my color-switching on `@text-color` instead of `@syntax-text-color`, which meant that for contrasting color schemes the colors came out wrong. Thanks for the report!

**Comment by X-G** [comment]
It works fine!
Thanks for your works on this wonderful package!
![qq 20150529193543](https://cloud.githubusercontent.com/assets/6829403/7888587/ea360a86-0639-11e5-8e70-918c57139295.png)

**Comment by willwhitney** [comment]
Awesome, glad I could take care of that for you!
