### ISSUE TITLE
Improved autocompletion (e.g. within nested expressions)

### ISSUE THREAD

**Issue by kaibioinfo** [willwhitney/hydrogen#50]
Currently, autocompletion is only working for the first identifier within a line. For example: writing
```python
  x = [1,2,3]
  x.a
```
starts autocompletion and suggest **a.append**.

However, the following does not work:
```python
  x = [1,2,3]
  x.append(x.rev
```

I guess the reason for this is the getPrefix function in autocomplete-provider.coffee. This regexp searches for the FIRST identifier to autocomplete, instead of using the the last identifier before cursor position.

**Comment by willwhitney** [comment]
Quite right. I messed this up in the last little edit I made to the autocomplete regex.
