### ISSUE TITLE
Installation error (OSX Yosemite, Atom Version 0.206.0)

### ISSUE THREAD

**Issue by JavierMares** [willwhitney/hydrogen#51]
The following error shows upon installation (pkg-config is in fact installed and working, as far as I can tell):

> zmq@2.11.1 install /private/var/folders/wk/59lcnyg524q1zgyydwn8qgnr0000gn/T/apm-install-dir-11555-22648-1421byw/node_modules/Hydrogen/node_modules/zmq
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/wk/59lcnyg524q1zgyydwn8qgnr0000gn/T/apm-install-dir-11555-22648-1421byw/node_modules/Hydrogen/node_modules/zmq
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/javier/.atom/.apm/.apmrc" "--userconfig" "/Users/javier/.atom/.apmrc" "install" "/private/var/folders/wk/59lcnyg524q1zgyydwn8qgnr0000gn/T/d-11555-22648-y2knes/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.11.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/wk/59lcnyg524q1zgyydwn8qgnr0000gn/T/apm-install-dir-11555-22648-1421byw/npm-debug.log

The log file npm-debug.log is not present, and neither is it's subfolder.

Thank you in advance,
Javier

**Comment by JavierMares** [comment]
Unaccountably, it works. The only difference is that I ran atom from the terminal.

**Comment by willwhitney** [comment]
This is a known issue — Atom only has your `$PATH` if it's started from the command line, so it won't be able to find tools like `pkg-config` during installation. I have an issue open on Atom about this (https://github.com/atom/atom/issues/6956), so hopefully it can get taken care of.

I just added a note in the readme to make that clearer to all future installers. Sorry for the inconvenience!

**Comment by JavierMares** [comment]
Thanks @willwhitney !
