### ISSUE TITLE
Error with pkg-config when installing on OS X

### ISSUE THREAD

**Issue by stared** [willwhitney/hydrogen#54]
When I try to install hydrogen I am getting the following error:

    > zmq@2.11.1 install /private/var/folders/3g/gp3lt1950195fs3kf27csb0h0000gn/T/apm-install-dir-11559-43382-ne5xq1/node_modules/Hydrogen/node_modules/zmq
    > node-gyp rebuild

    /bin/sh: pkg-config: command not found
    gyp: Call to 'pkg-config libzmq --libs' returned exit status 127. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Darwin 12.6.0
    gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /private/var/folders/3g/gp3lt1950195fs3kf27csb0h0000gn/T/apm-install-dir-11559-43382-ne5xq1/node_modules/Hydrogen/node_modules/zmq
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    npm ERR! Darwin 12.6.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/username/.atom/.apm/.apmrc" "--userconfig" "/Users/username/.atom/.apmrc" "install" "/private/var/folders/3g/gp3lt1950195fs3kf27csb0h0000gn/T/d-11559-43382-4rvrhq/package.tgz" "--target=0.22.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! zmq@2.11.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the zmq@2.11.1 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the zmq package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls zmq
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/var/folders/3g/gp3lt1950195fs3kf27csb0h0000gn/T/apm-install-dir-11559-43382-ne5xq1/npm-debug.log

I do have `brew`-installed `zeromq` (4.0.5_2) and `pkg-config` (0.28). I am on OS X 10.8.5.
Plus, `pkg-config` *is* accessible from command line.

**Comment by rgbkrk** [comment]
First thing - make sure to run atom from the command line:

```
$ atom .
```

Second, try installing it from the command line
```
$ apm install hydrogen
```

**Comment by stared** [comment]
Thanks. Installing through command line works (and I got no warning or errors).

But in Atom it works (i.e. executes lines, provides autocompletion) but instead of results shows white boxes. (As it *might* be related to my previous problem, I keep this in this thread.) Do you have any ideas what it is?

![screen shot 2015-06-09 at 17 12 35](https://cloud.githubusercontent.com/assets/1001610/8061384/d9e89448-0eca-11e5-846c-0ec5fd1ab024.png)

**Comment by rgbkrk** [comment]
Hmm, I see white on white results there. This looks like a theming misalignment.

**Comment by stared** [comment]
I see - it is a different thing. I tried to change styles and for light themes it works; for all dark themes I have it is unreadable (for Monokai - almost visible).

But in this case - isn't it an issue with box color? (How can it be styled?)

(And for the main topic - any ideas why from-Atom installation did not work for me (permissions? different stuff?).)

**Comment by willwhitney** [comment]
Per the readme, 

> Assuming you followed the dependencies steps above, you can now `apm install hydrogen` (recommended) or search for "hydrogen" in the Install pane of the Atom settings. Note that installing from within Atom will only work if you start Atom from the command line! See [Jank](https://github.com/willwhitney/hydrogen#jank).

One of our dependencies needs an external build tool, and Atom only has your `$PATH` if run from the command line.

This is looks like an issue with my styling logic (it tries to select colors that match your background). What UI theme and syntax theme are you using? I'll fix that up ASAP.

**Comment by stared** [comment]
@willwhitney I don't know why I missed the last sentence, my bad.

(Maybe because it was not near to command line commands or because I didn't know command line installation for atom, let alone - that it is different.)

**Comment by willwhitney** [comment]
No worries! 

What UI theme and syntax theme are you using?

**Comment by stared** [comment]
Atom Dark / Monokai.

**Comment by willwhitney** [comment]
If it's [this monokai](https://github.com/burntime/atom-monokai), it fails to declare the global [syntax color variables](https://github.com/atom/one-dark-syntax/blob/master/styles/syntax-variables.less) that Hydrogen depends on.

I guess I'll just make Hydrogen use the same colors no matter what, maybe attempting to pick one of two themes based on the syntax colors if possible. I have to assume that other themes are going to have this problem as well.

**Comment by willwhitney** [comment]
Okay, I just pushed a patch that fixes up the color selection code a little bit. I think that should take care of it — thanks for reporting the issue!
