### ISSUE TITLE
No Auto-Complete on R Kernel

### ISSUE THREAD

**Issue by ChappedSky** [willwhitney/hydrogen#56]
I'm getting no auto complete of dataframes/lists on the R kernel (using the $ symbol for referencing).  Not sure if this hasn't been implemented yet or if I've borked something up.

**Comment by willwhitney** [comment]
Can you give me a test case? I don't know much about R, but I'm betting it's the $ delimiter confusing the regex.

**Comment by ChappedSky** [comment]
Sure, in a hydrogen hooked to a R kernel:
```
data(iris)
iris$ 
```
It should autocomplete after the $ with the following options: iris$Petal.Length  iris$Petal.Width   iris$Sepal.Length  iris$Sepal.Width   iris$Species

**Comment by rgbkrk** [comment]
![screenshot 2015-06-11 13 58 07](https://cloud.githubusercontent.com/assets/836375/8115536/b0c9dba8-1041-11e5-84ef-61b2f72c1bee.png)

**Comment by willwhitney** [comment]
Ok, was just what I thought. Thanks for reporting the issue!

**Comment by rgbkrk** [comment]
PHP for that matter too.

**Comment by willwhitney** [comment]
Oh no, I'll have to allow for $ at the beginning too...

**Comment by rgbkrk** [comment]
Yup, there is an [IPHP kernel](https://github.com/dawehner/ipython-php) though it hasn't been touched since July 2014 and is reliant on IPython 2.x.

This is where I wonder if there's a way to rely on the grammars and autocomplete providers more directly...

**Comment by ChappedSky** [comment]
Awesome! Thanks for the fix

**Comment by n-riesco** [comment]
and Javascript

**Comment by n-riesco** [comment]
This is the regexp I'm using in IJavascript:

https://github.com/n-riesco/nel/blob/master/lib/nel.js#L713

**Comment by rgbkrk** [comment]
Oh yeah, JavaScript. Silly me.

**Comment by willwhitney** [comment]
We're going to need to break all these regexes out by language per https://github.com/willwhitney/hydrogen/issues/63. I'll change the code in `autocomplete-provider.coffee` to this format, then people can add and amend languages as needed.

**Comment by willwhitney** [comment]
This is happening — please suggest changes any changes to the regexes defined in [`autocomplete-provider.coffee`](https://github.com/willwhitney/hydrogen/blob/master/lib/autocomplete-provider.coffee) over in #63.

@n-riesco thanks for the JS regex!
