### ISSUE TITLE
Salvaging an IPython session from a frozen Atom

### ISSUE THREAD

**Issue by tscholak** [willwhitney/hydrogen#57]
Is there any way I can salvage a still running python backend if Atom locked up completely (but hasn't crashed)? Can I connect the python session to a CLI somehow?

I have been running a program for a while now and I don't want to loose my results.

**Comment by willwhitney** [comment]
The IPython kernel saves out a file for reconnection — if it's still running, I *think* you can reconnect to it. When you run a kernel directly, it spits out a message like this:

```
To connect another client to this kernel, use:
    --existing kernel-15035.json
```

The file is (for me) saved in `/Users/will/.ipython/profile_default/security` and is called `kernel-XXXXX.json`. If you find the most recent one of those in the folder, then you can run `ipython console --existing kernel-15035.json` to connect to it.

**Comment by willwhitney** [comment]
I just tried this with a kernel started by Hydrogen and it worked. You can even run `%history` to get the list of recently-run commands.

**Comment by tscholak** [comment]
That is interesting. I just gave that a try. It seems I can connect,
```
$ ipython console --existing kernel-59784.json
IPython Console 3.1.0
```
but I don't get further than that. Maybe I should say that the python script is still running. I want to interrupt it, pickle as much as I can, and then restart atom.

**Comment by willwhitney** [comment]
Maybe you can send an interrupt to the kernel manually — you can `ps aux | grep python`, then (double-check this) `kill -2 <process number>`.

**Comment by tscholak** [comment]
Success! Thanks a lot!
Hope that will help others, too.
