### ISSUE TITLE
/bin/sh: pkg-config: command not found

### ISSUE THREAD

**Issue by davidthewatson** [willwhitney/hydrogen#58]
I've got atom Version 0.209.0 (0.209.0) on Mac OS X 10.10.3.

I had hydrogen 0.3.3 installed. When I try to upgrade to 0.3.15 I get pkg-config command not found. I uninstalled hydrogen and tried installing from scratch. Same thing.

pkg-config appears to be fine at the terminal:

    08:25 $ pkg-config 
    Must specify package names on the command line
    ✘-1 ~ 
    10:13 $ which pkg-config
    /usr/local/bin/pkg-config

Here's the output from install:

    Installing “Hydrogen@0.3.15” failed.Hide output…

    > zmq@2.11.1 install /private/var/folders/1p/38rnnlmx6hz5n9w8d3h19ks40000gn/T/apm-install-dir-115512-2651-ztsswl/node_modules/Hydrogen/node_modules/zmq
    > node-gyp rebuild

    /bin/sh: pkg-config: command not found
    gyp: Call to 'pkg-config libzmq --libs' returned exit status 127. while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Darwin 14.3.0
    gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /private/var/folders/1p/38rnnlmx6hz5n9w8d3h19ks40000gn/T/apm-install-dir-115512-2651-ztsswl/node_modules/Hydrogen/node_modules/zmq
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    npm ERR! Darwin 14.3.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/dwatson/.atom/.apm/.apmrc" "--userconfig" "/Users/dwatson/.atom/.apmrc" "install" "/private/var/folders/1p/38rnnlmx6hz5n9w8d3h19ks40000gn/T/d-115512-2651-jfwvhe/package.tgz" "--target=0.22.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! zmq@2.11.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the zmq@2.11.1 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the zmq package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls zmq
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/var/folders/1p/38rnnlmx6hz5n9w8d3h19ks40000gn/T/apm-install-dir-115512-2651-ztsswl/npm-debug.log

**Comment by willwhitney** [comment]
Was Atom launched from the command line when you tried to update? Does `apm install hydrogen` work?

**Comment by davidthewatson** [comment]
No, but that worked. Thanks!

David Watson
http://davidwatson.org/

**Comment by willwhitney** [comment]
Ah, the perennial issues with `node-gyp`.

Glad that worked for you!

**Comment by xpluscal** [comment]
I get the same issues when trying to install via ```apm install hydrogen```. any ideas?

**Comment by xpluscal** [comment]
Sorry, it was due to pkg-config not being installed via brew as pointed out in your guide. Solved.
