### ISSUE TITLE
Ipython kernel not showing output on linux 

### ISSUE THREAD

**Issue by albop** [willwhitney/hydrogen#61]
On my machine Ubuntu-15.04 with latest anaconda, I get a check mark for each line that is run, not the output (see figure). It seems that the commands are running fine though, since there is auto-completion and I can interact with the kernel using a console. Any idea ?

![no_output](https://cloud.githubusercontent.com/assets/276777/8146023/22cc6e64-11f0-11e5-84cb-a2ebb0d28daa.png)

**Comment by n-riesco** [comment]
What version of ipython are you using (`ipython --version`)?

**Comment by willwhitney** [comment]
@albop also curious what IPython version you've got. Can you send me that, along with a screenshot of the Atom console (View > Developer > Toggle developer tools > hit console tab) after running some code?

**Comment by albop** [comment]
I have IPython 3.1:
```
  ~  ipython
Python 2.7.10 |Anaconda 2.2.0 (64-bit)| (default, May 28 2015, 17:02:03) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: 
```

Here is a screenshot with developper panel:

![with_log](https://cloud.githubusercontent.com/assets/276777/8171358/4d336644-1385-11e5-8909-c297ed52bf08.png)

**Comment by willwhitney** [comment]
Can I get you to hit the expand arrow on those "shell message: ▶ object" lines?

**Comment by albop** [comment]
Here is one screenshot: 
![screen_1](https://cloud.githubusercontent.com/assets/276777/8194334/071811ea-1449-11e5-8384-ca9037c9637a.png)

By curiosity, I tried to understand what happens in `kernel.coffee`. It looked like the functions `onIOMessage` and `onShellMessage` were never called. Googling `atom+github+socket` and finding I came to suspect a problem with `libuv`.

I still have no idea of what is really going on, but upgrading from libuv1-dev to libuv3-dev fixed the bug.

**Comment by willwhitney** [comment]
That is very nasty. I'm glad it works now!

**Comment by YoungxHelsinki** [comment]
I installed hydrogen on Ubuntu 12.4.05 64bit. I have Ipython 3.2.0.

My problem is not about installation but the excution of hydrogen.
I don't get any error when I hit ctrl-alt-enter, but an infinite loading symbol comes next to the code.
I tried to install libuv3-dev by 'sudo apt-get install libuv3-dev' but I get 'unable to locate the package'.

Does anyone have any idea?

**Comment by willwhitney** [comment]
Did they rename things recently? http://packages.ubuntu.com/search?suite=wily&arch=any&mode=filename&searchon=contents&keywords=libuv

**Comment by YoungxHelsinki** [comment]
Sorry for the late response. I didn't need ubuntu at work so I didn't look at this issue anymore.
