### ISSUE TITLE
custom prefix regexes for every language

### ISSUE THREAD

**Issue by willwhitney** [willwhitney/hydrogen#63]
Per https://github.com/JuliaLang/atom-language-julia/issues/7#issuecomment-112096433, having one regex that finds the autocomplete prefix for every language breaks things when it matches things which aren't valid in that language.

Instead we need to have a dictionary mapping language name to regex, e.g.

```javascript
{
  'python': /([\w0-9_-][\.]?)+$/
}

**Comment by rgbkrk** [comment]
:+1:

**Comment by willwhitney** [comment]
OK, this is happening — please suggest changes to the regexes defined in [`autocomplete-provider.coffee`](https://github.com/willwhitney/hydrogen/blob/master/lib/autocomplete-provider.coffee) in this thread.

**Comment by rgbkrk** [comment]
The Python regex works for Python2 but not for [Python3](https://docs.python.org/3/reference/lexical_analysis.html#identifiers) which allows a certain subset of Unicode characters. The spec is just so darn exciting that I wouldn't know how to implement it in JavaScript though.

**Comment by spencerlyon2** [comment]
In the [julia grammar](https://github.com/JuliaLang/atom-language-julia/blob/master/grammars/julia.cson#L126) I'm using  `([\w.!]+)` to capture function names. Functions and variables can have the same characters, so this should work for you. You might need to modify slightly by appending a `$` or such.

(NOTE: the `\w` matches digits, unicode, and underscores in addition to standard letters, [see here](http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt) )

**Comment by willwhitney** [comment]
@spencerlyon2 yup, you're right. I had changed the Julia one a bit from that but there are other places where I've still got `\w0-9_`. This will work for code most people actually like, but let me know if you come across a regex that handles the Unicode points too.

@rgbkrk Python3 has the same issue as Julia.

Regex were really not designed for unicode...

**Comment by spencerlyon2** [comment]
I have some specs in the julia-language package that check to make sure the `\w` also matches unicode.

See [here](https://github.com/JuliaLang/atom-language-julia/blob/master/spec/julia-spec.coffee#L56)

**Comment by willwhitney** [comment]
Oh hell yeah! I didn't expect that to work.

Thanks @spencerlyon2!

**Comment by spencerlyon2** [comment]
No problem, glad it is an easy solution. I was just about as excited to learn about that too :smirk:

**Comment by spencerlyon2** [comment]
Quick note. I know the grammars use Onigurama regex engine. I don't know which regex library powers other packages (i would expect it to be the same, but maybe other they use built in (coffee|java)script regex engine - if such a thing exists).

 It might be worthwhile to do a quick test that Onigurama is used throughout before considering that issue solved.

**Comment by willwhitney** [comment]
Oh good grief. The built-in JS regexes don't have this behavior. I'd just `require 'oniguruma'`, but it's built with `node-gyp`, and I don't want to take us further down that rabbit hole.

**Comment by spencerlyon2** [comment]
Ouch that sucks.

[first-mate](https://github.com/atom/first-mate) is the atom package that provides support for text mate grammars. Because they are already including Onigurama you can just figure out a way to use their install? If nothing else it might give an idea for the easiest way to do that if you need to.

**Comment by spencerlyon2** [comment]
At one point the previous language-julia package had `\u0021-\uFFFF` in the regex scope function names. This did catch unicode, but it also caused bugs like [this one](https://github.com/tpoisot/language-julia/issues/8). As you can see by the highlighting in the picture on that link, the unicode sequence I just gave somehow matched `warn("$(string` as the function name when it should have only matched `warn`. 


Since you are just providing a list of completions maybe it would be ok to just live with that problem?

**Comment by willwhitney** [comment]
Yeah, having slightly greedy matches is fine for this, since the kernel will still only return valid completions. I think I'll go with that.

**Comment by willwhitney** [comment]
After reading the spec some I've arrived at the terrifying `/([^\d\W]|[\u00A0-\uFFFF])[\w.!\u00A0-\uFFFF]*$/`.

I think the same thing, minus the `!`, is a tolerable first pass for Python3.

**Comment by rgbkrk** [comment]
That's awesome. Not that it helps me, but this is especially useful for the non-English speaking folk.

**Comment by willwhitney** [comment]
Just shipped this live! Please let me know if it does anything weird.

Pull requests fixing these regexes or adding new languages will be gratefully accepted!
