### ISSUE TITLE
Using remote ipython notebook executed within a docker image

### ISSUE THREAD

**Issue by trbck** [willwhitney/hydrogen#65]
I want to connect hydrogen to ipython instance executed within a docker container since I want to keep my dev environment separated from the rest. I a was trying to manipulate the kernel.json file in kernel-configs but it just does not work.

Running ipython instance settings in docker container:
```
ipython kernel --no-secure --hb=54924 --control=54925 --shell=54926 --stdin=54927 --iopub=54928 --   colors=NoColor --ip=0.0.0.0`
```
Edited kernel.json string:
```
{"version":5,"key":"","signature_scheme":"hmac-sha256","transport":"tcp","ip":"127.0.0.1","hb_port":54924,"control_port":54925,"shell_port":54926,"stdin_port":54927,"iopub_port":54928}
```

From my understanding this should work, but it does not :)

**Comment by willwhitney** [comment]
The files in `kernel-configs` are created by Hydrogen and read in by the kernel, not the other way around.

Instead, you could go to `~/.ipython/kernels` and create a new folder with a `kernel.json` (a "kernelspec") in it. Then the `argv` field should be a command which will start the kernel within the container and use the specified `connection_file`.

For example, here's the IJavascript kernelspec:
```json
{
  "argv": [
    "node", 
    "/usr/local/lib/node_modules/ijavascript/lib/kernel.js", 
    "/Users/will/code/ijavascript", 
    "{connection_file}", 
    "--protocol=5.0"
  ], 
  "display_name": "Javascript (Node.js)", 
  "language": "javascript"
} 
```

Does that make sense?
