### ISSUE TITLE
[Error] ipython could not be spawned

### ISSUE THREAD

**Issue by YoungxHelsinki** [willwhitney/hydrogen#67]
Hi guys, 

I followed the Hydrogen installation guide on Mac OS X 10.10.3
When I run Python codes, it prompts an error: "'ipython' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."
![screen shot 2015-06-27 at 1 05 05 pm](https://cloud.githubusercontent.com/assets/5738363/8390414/4369269c-1cce-11e5-8f5c-2818c78b2529.png)

This is weird because I can launch ipython on terminal and emacs.
I checked python path with 'sys.path':

['', '/usr/local/bin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.46.0-py2.7.egg', '/Library/Python/2.7/site-packages/pyechonest-8.0.2-py2.7.egg', '/Library/Python/2.7/site-packages/howdoi-1.1.7-py2.7.egg', '/Library/Python/2.7/site-packages/requests_cache-0.4.9-py2.7.egg', '/Library/Python/2.7/site-packages/requests-2.6.0-py2.7.egg', '/Library/Python/2.7/site-packages/Pygments-2.0.2-py2.7.egg', '/Library/Python/2.7/site-packages/pyquery-1.2.9-py2.7.egg', '/Library/Python/2.7/site-packages/cssselect-0.9.1-py2.7.egg', '/Library/Python/2.7/site-packages/lxml-3.4.2-py2.7-macosx-10.10-intel.egg', '/usr/local/lib/python2.7/site-packages/selenium-2.46.0-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/IPython/extensions', '/Users/young/.ipython']

So ipython seems to be in my path.
I wonder what went wrong :(

**Comment by willwhitney** [comment]
Hmm...

Did you try killing Atom entirely and running it from the command line? If Atom is run as an app, it can't see your `$PATH`. If that doesn't work...

In the Atom console, can you run these tests?

```javascript
childProcess = require('child_process')

childProcess.execSync("which ipython").toString()
// => "/usr/local/bin/ipython"

childProcess.spawnSync("ipython").stdout.toString()
// => the IPython console header
```

Just trying to figure out what Atom can and can't see right now.

**Comment by YoungxHelsinki** [comment]
Hei willwhitney,

Thanks for the reply! It works like a charm after I killed Atom. 
I thought reload would be enough but apparently it wasn't.
Ipython UI is little different from what I expected.
Does Hydrogen support an ipython shell that is hooked up with Atom?
For instance in emacs I could do:
![screen shot 2015-06-28 at 8 55 28 pm](https://cloud.githubusercontent.com/assets/5738363/8396222/2a9dd404-1dd8-11e5-98fb-f98ee8f351d5.png)

In the upper pane I have a script opened and ipython shell in the below. I could run the script codes selectively on ipython shell. I think being able to use the shell comes quite handy when you try to fix an error.

Thanks for the great package anyway! :)

**Comment by willwhitney** [comment]
Glad it worked!

Hydrogen starts its own kernels and doesn't use an IPython server at all. 

However, you can start an IPython server and ask it to connect to Hydrogen's kernels. When you first run something on a kernel in Hydrogen, it logs out the line "Kernel configuration file path: <path-to-config>.json". You can start an `ipython console` connected to the same kernel by running `ipython console --existing <path-to-config>.json`.

**Comment by YoungxHelsinki** [comment]
@willwhitney Can you elaborate on connecting the same kernel? I've never worked with kernels so I have no idea what you are talking about :(

**Comment by willwhitney** [comment]
@YoungxHelsinki in Atom you can open the dev console (View > Developer > Developer tools, open Console tab) and then run some code with Hydrogen as usual. When Hydrogen starts a Python kernel, the kernel will output a long message in the Atom console that looks like this:

```
kernel process received on stdout: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049

To connect another client to this kernel, use:
    --existing /Users/will/code/hydrogen/kernel-configs/kernel-780edb36-8aa4-4828-aa4f-5cfc60ca78d3.json
```

Then you can run `ipython console --existing /Users/will/code/hydrogen/kernel-configs/kernel-780edb36-8aa4-4828-aa4f-5cfc60ca78d3.json` to start an IPython console connected to that kernel. That is, all the code you run in either IPython console or Hydrogen will be run in the same namespace; you can run `x=4` in Hydrogen, and `print(x)` in IPython will give `4`.

That make sense?

**Comment by YoungxHelsinki** [comment]
@willwhitney I couldn't find the Developer tools section on my Atom. 
My Atom is 1.0.3 and I use Mac OS X 10.10.4.
I also tried to open the repository in developer mode and find Developer tools but that didn't succeed either.

![screen shot 2015-08-10 at 5 19 04 pm](https://cloud.githubusercontent.com/assets/5738363/9163173/f1033f72-3f83-11e5-817f-db36cdf91800.png)

**Comment by willwhitney** [comment]
Does it not work when you click "Toggle Developer Tools" in that menu?

**Comment by YoungxHelsinki** [comment]
Thanks for the comment Will!
Ok I saw the console window but my console wouldn't show the same output like yours.
Instead it looks like the screenshot.

![screen shot 2015-08-11 at 2 07 23 pm](https://cloud.githubusercontent.com/assets/5738363/9190638/5ed7b59c-4032-11e5-9a4d-3c9168a63325.png)

I also tried to find hydrogen directory by 
```bash
sudo find . -type d | grep 'hydrogen'
```
on my terminal but coudln't find .../hydrogen/kernel-configs/...

**Comment by YoungxHelsinki** [comment]
I found something more and I will post when my meeting ends :)

**Comment by YoungxHelsinki** [comment]
Ok I solved the issue.
My iPython kernel jsons reside in 
```
~/.ipython/profile_default/security/
```
And "the message":
```
kernel process received on stdout: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.
....
```
only appeared at the beginning of execution of hydrogen.
Thanks a lot for your patience Will but can you explain how it works under the hood? What do those json files do?

**Comment by BrianMiner** [comment]
I have the same problem....The ipython kernel cant be located using hydrogen. I can run the "what atom can see" commands above and I get the following. I have tried rebuilding, reinstalling and I can not get python to work.

childProcess = require('child_process')
Object {}
childProcess.execSync("which ipython").toString()
"/home/jma/anaconda/bin/ipython
"
childProcess.spawnSync("ipython").stdout.toString()
"Python 2.7.11 |Anaconda 2.1.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

[0;32mIn [[1;32m1[0;32m]: [0m
Do you really want to exit ([y]/n)? 
"

**Comment by rgbkrk** [comment]
@BrianMiner From the command line (within your conda environment), can you run:

```
python -m ipykernel install --user
```

**Comment by BrianMiner** [comment]
/home/jma/anaconda/bin/python: No module named ipykernel

**Comment by BrianMiner** [comment]
I thought the package worked with Ipython I did not realize I needed to upgrade to jupyter. That solved it!

**Comment by accmohamedsaber** [comment]
Hi,
I am getting this error message, as shown in the print screen, when I installed Atom on Windows, could you please help? 

![image](https://user-images.githubusercontent.com/29353784/30767472-a6020598-9ff4-11e7-9cf5-9254aaed4931.png)

**Comment by nicholascgilpin** [comment]
Encountered in Atom version 1.29 8/2/2018 on Windows 10
I'm adding this comment because the error message is unintuitive. The error still appears with Python installed and in the PATH. However, the issue can be easily solved as shown below.

Error Message:
'C:\Users\my_username\AppData\Local\Programs\Python\Python36-32\python.exe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

My Solution: Reinstall the kernel onto your current environment.
python -m pip install ipykernel
python -m ipykernel install --user
