### ISSUE TITLE
help with instalation, zmq and python related...

### ISSUE THREAD

**Issue by razvanc87** [willwhitney/hydrogen#68]
Please help me... I have tried everything, including:

* running with `PYTHON=python apm...`
* setting `apm config set python /path/to/python`

and still desn't work. I'm not entirely sure how this is connected to python cause it's the first time I'm using it and in the build (from `apm`) I don't get any reference to python. The package installs in `atom` but when I open it it says incompatible packages: `zmq@2.11.1 - Error message: libzmq.so.5: cannot open shared object file: No such file or directory`.

Now I go in `$HOME/.atom/packages/Hydrogen/node_modules/zmq/build/Release` and do:
```
razvan@laptop:~/.atom/packages/Hydrogen/node_modules/zmq/build/Release$ ldd zmq.node 
	linux-vdso.so.1 =>  (0x00007ffcea79b000)
	libzmq.so.5 => /home/razvan/.local/lib/libzmq.so.5 (0x00007fcdbb9be000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcdbb6af000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcdbb498000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcdbb0ce000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcdbaec6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcdbaca7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcdba99f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcdbbe41000
```

But if I try and run the executable I just get a `Segmentation fault (core dump)` error. Now I do:
```
razvan@laptop:~/.atom/packages/Hydrogen/node_modules/zmq/build/Release$ gdb ./zmq.node 
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.4/site.py", line 586, in <module>
    main()
  File "/usr/lib/python3.4/site.py", line 572, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.4/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.4/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.4/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.4/sysconfig.py", line 597, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.4/sysconfig.py", line 540, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.4/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.4/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'
```

And get this strange error about python3.4, but I can run... `python3 -m site` with no problem:
```
razvan@laptop:~/.atom/packages/Hydrogen/node_modules/zmq/build/Release$ python3 -m site
sys.path = [
    '/home/razvan/.atom/packages/Hydrogen/node_modules/zmq/build/Release',
    '/home/razvan/.local/lib/python3.4/site-packages/pip-7.0.3-py3.4.egg',
    '/home/razvan/.local/lib/python3.4/site-packages/setuptools-17.1.1-py3.4.egg',
    '/home/razvan/.local/Cellar/python3/3.4.3/lib/python3.4/site-packages/pip-7.0.3-py3.4.egg',
    '/home/razvan/.local/Cellar/python3/3.4.3/lib/python3.4/site-packages/setuptools-17.1.1-py3.4.egg',
    '/home/razvan/.local/Cellar/python3/3.4.3/lib/python34.zip',
    '/home/razvan/.local/Cellar/python3/3.4.3/lib/python3.4',
    '/home/razvan/.local/Cellar/python3/3.4.3/lib/python3.4/plat-linux',
    '/home/razvan/.local/Cellar/python3/3.4.3/lib/python3.4/lib-dynload',
    '/home/razvan/.local/lib/python3.4/site-packages',
    '/home/razvan/.local/Cellar/python3/3.4.3/lib/python3.4/site-packages',
]
USER_BASE: '/home/razvan/.local' (exists)
USER_SITE: '/home/razvan/.local/lib/python3.4/site-packages' (exists)
ENABLE_USER_SITE: True
```

Further notes:
I run on latest Ubuntu and have installed python 2 & 3 locally with the help of `linuxbrew`. Also node is installed with `brew` and afterwards `node-gyp` with the local `npm` command, but if I'm not mistaking `apm` uses it's own `node-gyp` installation.. I uploaded the install log from `apm install --verbose hydrogen` [here](https://gist.github.com/razvanc87/8b58c3a9b9d0b336df9e).

Any help is greatly appreciated!

**Comment by razvanc87** [comment]
Well... sorry for my stupidity, it was my fault it seems. Atom complained that I had `zmq` linked against `libzmq.so.5` (provided by `brew`) which isn't compatible with the current atom build... so I installed `libzmq` system-wide from ubuntu repositories (`libzmq3`) which has a version about which atom doesn't complain...

Sorry for any inconvenience. I will follow your project very closely! Thanks.

**Comment by willwhitney** [comment]
Huh, glad you figured this out. Your work will probably help someone else in the future!
