### ISSUE TITLE
Pick up kernelspecs from Jupyter directories

### ISSUE THREAD

**Issue by rgbkrk** [willwhitney/hydrogen#7]
We'll need/want to search the new Jupyter paths as well for kernelspecs, just as in https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/paths.py

This is for the future release of the Jupyter packages (but my and the rest of the IPython/Jupyter team's likeliness to use this package).

**Comment by willwhitney** [comment]
Which of these directories contains the kernelspecs? `~/.jupyter`?

**Comment by rgbkrk** [comment]
Multiples. It's the aggregation of all of them...

```
In [1]: import jupyter_core.paths

In [2]: jupyter_core.paths.jupyter_path("kernels")
Out[2]:
['/Users/rgbkrk/Library/Jupyter/kernels',
 '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/share/jupyter/kernels',
 '/usr/local/share/jupyter/kernels',
 '/usr/share/jupyter/kernels']
```

This is where I was bantering around with creating a simple wrapper script that would dump JSON to stdout with options we'd need from an alternate front end (like Hydrogen). The other alternative is to use what we've got and launch a python kernel just for Hydrogen that queries for this same information.

It's either that or always searching particular paths.

**Comment by willwhitney** [comment]
Gosh, that's ugly. I'd sure love a script that dumps JSON of all the kernels' info.

**Comment by willwhitney** [comment]
Especially if that script worked across IPython and Jupyter.

**Comment by rgbkrk** [comment]
As the migration happens, IPython will just be one of the kernels for Jupyter. It's all the same team.

When I get some free time after work, I'll start poking at what scripts could be useful for Hydrogen and Jupyter sidecar to call out to Jupyter for accurate information.

**Comment by willwhitney** [comment]
What I mean is that I'd like this to still work for people who haven't
updated to a post-Split version. I find most people don't update until
something completely stops working.

Thanks!

**Comment by rgbkrk** [comment]
Totally, I'll end up making a script that straddles both.

Also, people are strange and install from master whether or not they're contributing to IPython/Jupyter. For this release it's a bit silly since it's mostly repackaging, but in previous versions it was a big delta.

**Comment by willwhitney** [comment]
Awesome!

For the moment I'm loading all kernels found in that list plus `~/.ipython/kernels` and `~/.jupyter/kernels`. Not a good answer, but it ought to tide us over for now. That's in the latest release.

**Comment by rgbkrk** [comment]
Done in #19.
