### ISSUE TITLE
Package Spawning Process problem

### ISSUE THREAD

**Issue by lseongjoo** [willwhitney/hydrogen#72]
How can I properly report this problem?

![2015-07-02 2 12 23](https://cloud.githubusercontent.com/assets/444818/8470333/685e69ae-20c4-11e5-9139-e0c613d467b8.png)

**Comment by willwhitney** [comment]
Did you kill all Atom processes and start it from the command line?

**Comment by lseongjoo** [comment]
I hope not. IPython is in PATH and I install the package. Then, reload Atom. That's all I did. 



2015. 7. 3. 오전 1:11 Will Whitney <notifications@github.com> 작성:

> Did you kill all Atom processes and start it from the command line?
>

**Comment by willwhitney** [comment]
You'll need to close Atom completely and then start it from the terminal (using the `atom` command). See [Jank](https://github.com/willwhitney/hydrogen#jank) for more info.

**Comment by rpavlick** [comment]
This could 'jank' could be avoided by using 'shell-environment'. 

https://www.npmjs.com/package/shell-environment

https://github.com/rgbkrk/atom-script/pull/98#issuecomment-49167626

**Comment by willwhitney** [comment]
Yes, we've discussed doing something similar before: https://github.com/willwhitney/hydrogen/pull/34

I have similar reservations for using this path as that one. I've also written this behavior up as a bug on Atom: https://github.com/atom/atom/issues/6956
