### ISSUE TITLE
Does not find correct Julia path!

### ISSUE THREAD

**Issue by JonnyCBB** [willwhitney/hydrogen#78]
I recently installed Atom 1.0, Julia v0.3.10 (On 2nd July 2015) and now installed the Hydrogen package (7th July 2015). I've managed to get Hydrogen to run Python code but I can't get it to run Julia code.

I get the error "Uncaught Error: spawn C:\\Users\\jonathan\\AppData\\Local\\Julia-0.3.6\\bin\\julia.exe ENOENT"

I don't have Julia v0.3.6 (I used quite long ago). 

I want it to point to C:\\Users\\jonathan\\AppData\\Local\\Julia-0.3.10\\bin\\julia.exe instead.

I'm running Windows 8 and I've checked my environment variables, it only have the path to Julia v0.3.10. 

Could there be a problem that means Hydrogen points to the wrong directory?

**Comment by willwhitney** [comment]
I believe you need to reinstall IJulia. When you install it, it writes a config file that Hydrogen uses which says how to launch it.

Let me know if that doesn't work and I'll reopen this.

**Comment by JonnyCBB** [comment]
Thanks for getting back to me so quickly. 

I tried what you recommended but it didn't work :(
Pkg.rm("IJulia")
Pkg.add("IJulia")
After doing that I even ran
Pkg.build("IJulia")
Pkg.update()
[All of the above was in a Julia terminal]

Then I tried to run a line of code in Atom but I got the same error message i.e. it's still trying to find Julia v0.3.6

**Comment by willwhitney** [comment]
OK, we'll need to dive a little deeper. If you run `ipython locate` at a prompt and open the directory it gives you, you should find a folder "kernels" inside. In that there should be a folder "julia 0.3".

In there, there should be a file `kernel.json` that looks like this:

```json
{
  "display_name": "Julia 0.3.7",
  "argv": [
    "/Applications/Julia-0.3.7.app/Contents/Resources/julia/bin/julia",
    "-i",
    "-F",
    "/Users/will/.julia/v0.3/IJulia/src/kernel.jl",
    "{connection_file}"
  ],
  "language": "julia"
}
```

You can modify this file to make it point to the right place for the `julia` binary. Assuming this is the problem.

**Comment by JonnyCBB** [comment]
I modified the file and it works.

However I found two folders in the Kernels directory. One named "julia 0.3" which pointed to Julia v0.3,6 and the other folder named "julia-0.3" which had the correct Julia version in there.
I assume there's either a new way of naming the folders or it saw the previous folder, decided not to overwrite it and create the new folder. I'm inclined to go with the former.

Anyway Thank you so much for the help.

I'll close the issue

**Comment by willwhitney** [comment]
That makes sense. The IJulia people must have changed their naming so it didn't update properly. Glad that fixed it!

**Comment by rgbkrk** [comment]
Ah, yeah. That was me. https://github.com/JuliaLang/IJulia.jl/pull/298

**Comment by mpf** [comment]
I'm also having the same trouble: `Hydrogen: Run` causes the following error:

```
'/usr/local/Cellar/julia/0.3.6_1/bin/julia' could not be spawned. 
Is it installed and on your path? If so please open an issue on
the package spawning the process.
```

This is for Atom 1.3.1 running on OSX with Julia 0.4.1. Reinstalling IJulia and editing `kernel.json`, as suggested above, doesn't make a difference. In case it helps, I can confirm that the Jupyter notebook is working, and the Julia 0.4.1 does appear as an option.

**Comment by terraqout** [comment]
@mpf As you can see you have '/usr/local/Cellar/julia/***0.3.6_1***/bin/julia and julia 0.4.1.

Execute ```ipython kernelspec list``` drop julia-0.3 kernelspec path:
```
  scala211        /home/vganzin/.ipython/kernels/scala211
  coffeescript    /home/vganzin/.local/share/jupyter/kernels/coffeescript
  javascript      /home/vganzin/.local/share/jupyter/kernels/javascript
  julia-0.4       /home/vganzin/.local/share/jupyter/kernels/julia-0.4
  julia-0.5       /home/vganzin/.local/share/jupyter/kernels/julia-0.5
...

$ rm /home/vganzin/.local/share/jupyter/kernels/julia-0.4 -rf
```
After that your default julia kernel spec should be julia-0.4. If you successfully run ```Pkg.build()``` to rebuild ijulia for a new version, you would be able to use it with hydrogen.

**Comment by mpf** [comment]
@terraqout  Thanks for pointing out `ipython kernelspec list`, which pointed me to extraneous dirs in `~/Library/Jupyter/kernels`. Removing these fixed the problem.
