### ISSUE TITLE
ENH: set working directory

### ISSUE THREAD

**Issue by spencerlyon2** [willwhitney/hydrogen#8]
It would be great if we could set the working directory to be the file directory when a kernel is started.

**Comment by willwhitney** [comment]
That's a really good point. @rgbkrk, know if there's a way to do that consistently across kernels? It's not in the messaging spec.

**Comment by rgbkrk** [comment]
This is actually related to where the kernel itself gets launched, iirc.

That's more of an issue for the subprocess or BufferedProcess spawning from node. I'll check this out though.

**Comment by willwhitney** [comment]
Ah, you're right. I can set a working directory for the child process. Closed by 23446f7a641df0ce4aca21bee36a0a3305def6df.
