### ISSUE TITLE
Plots are opened in seperate figure window

### ISSUE THREAD

**Issue by JonnyCBB** [willwhitney/hydrogen#80]
When I run some Python code to plot graphs they open in a new figure window (even in the toggle window). 
Is there something I'm doing wrong?

**Comment by willwhitney** [comment]
Just like normally in IPython, you'll need to use `%matplotlib inline` to show plots inline. Without that the kernel thinks it should start a new window for it.

**Comment by JonnyCBB** [comment]
Thanks. Much appreciated :+1:
