### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by thomasingalls** [willwhitney/hydrogen#82]
Not sure if this is a duplicate of #5, but the trace looks different to me.

I can see that Hydrogen successfully starts a Julia kernel, for example, but I can't get any output to display.

*[Enter steps to reproduce below:]*

Happens on any python, Julia, or R file whenever I try to run *any* code.

**Atom Version:** 1.0.2
**System:** Mac OS X 10.9.5
**Thrown From:** Hydrogen package, v0.4.2

/Users/thomasingalls/.atom/packages/Hydrogen/lib/kernel.coffee:321
Hide Stack Trace
TypeError: Cannot read property 'toLowerCase' of undefined
  at /Users/thomasingalls/.atom/packages/Hydrogen/lib/kernel.coffee:321:29
  at Array.filter (native)
  at Kernel.module.exports.Kernel.getGrammarForLanguage (/Users/thomasingalls/.atom/packages/Hydrogen/lib/kernel.coffee:319:56)
  at new Kernel (/Users/thomasingalls/.atom/packages/Hydrogen/lib/kernel.coffee:21:20)
  at Object.module.exports.KernelManager.startKernel (/Users/thomasingalls/.atom/packages/Hydrogen/lib/kernel-manager.coffee:119:22)
  at /Users/thomasingalls/.atom/packages/Hydrogen/lib/main.coffee:255:44
  at /Users/thomasingalls/.atom/packages/Hydrogen/lib/config-manager.coffee:23:13
  at Object.module.exports.portfinder.findManyHelper (/Users/thomasingalls/.atom/packages/Hydrogen/lib/find-port.coffee:21:13)
  at /Users/thomasingalls/.atom/packages/Hydrogen/lib/find-port.coffee:26:18
  at Server.<anonymous> (/Users/thomasingalls/.atom/packages/Hydrogen/lib/find-port.coffee:14:21)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1443:10
  at process._tickCallback (node.js:357:13)

**Comment by nbren12** [comment]
I am getting the exact same error message for every kernel I have tried python2, python3, and julia. I am using anaconda on mac os x with python3 as my default.

**Comment by willwhitney** [comment]
It looks from [this line](https://github.com/willwhitney/hydrogen/blob/master/lib/kernel.coffee#L321) like the issue is that you have a grammar installed that doesn't have a "name" field. I'll add a check for that.

**Comment by willwhitney** [comment]
Published that check as `v0.4.4`. Can you update and tell me if that helps?

**Comment by nbren12** [comment]
It works now! however, I just `rm -rf'd` all the language-* packages in my
.atom folder, so I am not really sure which grammar was messing it up, and
whether this change fixes it (sorry). Now I just, have to figure out how to
run the python3 kernel.

**Comment by willwhitney** [comment]
Well, that seems like a good sign, at least.

To run Python 3 instead of Python 2, you can run `ipython kernelspec install-self`. This will make a folder in `/usr/local/share/jupyter/kernels`. (If it installs a Python 2 kernelspec, you can just rename it and make the first line of `argv` in the `kernel.json` file point to your Python 3 executable instead.)
