### ISSUE TITLE
Choose between different kernels (e.g. python2 and python3)

### ISSUE THREAD

**Issue by sebastjaeger** [willwhitney/hydrogen#84]
Hey,

let me start by saying that I really love your package!

Currently, I have to work with Python 2 as well as Python 3. As far as I understand, the kernel to be called is determined by the current grammar. Since the grammar is the same for python 2 and python 3, you always end up with one kernel (which depends on the kernel config).

If it was possible to explicitly choose the kernel that you want to use, this issue could be avoided.

**Comment by willwhitney** [comment]
Yes, this is definitely a problem. This change is coming as part of a
larger architectural change breaking things up into separate packages.

If you're interested in contributing this change before I get there, it
would be very welcome. I'd be happy to point you in the right direction!

**Comment by terraqout** [comment]
Fix https://github.com/willwhitney/hydrogen/pull/138

**Comment by slavaGanzin** [comment]
in master
