### ISSUE TITLE
results bubbles flicker when near screen edges

### ISSUE THREAD

**Issue by ssfrr** [willwhitney/hydrogen#93]
If I have a result bubble that is near the edge of the window it often flickers back and forth for a while before settling. This is particularly an issue with large output boxes that are more likely to be crossing the edge boundary.

It seems to interact with autocomplete popups, where if there is an output bubble near the autocomplete location, both the bubble and the autocomplete box flicker back and forth for a while.

**Comment by ssfrr** [comment]
Hmm, after clearing all output it doesn't seem to be happening now that there are only a couple output bubbles. Maybe it has something to do with having a bunch of displayed bubbles?

**Comment by willwhitney** [comment]
I've seen this — I'm pretty sure it's a bug with Atom's (Webkit/Blink/whatever) layout engine. Any overlay marker decoration is going to have this problem.

I'm going to close this issue here since it's not a Hydrogen issue, but please [file an issue against Atom](https://github.com/atom/atom/issues)!

**Comment by ssfrr** [comment]
Filed the issue, please feel free to add to it if you have any more insight.

I did see [this comment](https://github.com/atom/autocomplete-plus/blob/42660ee4d794d1403881a9fc20fadfb29014f96e/lib/suggestion-list-element.coffee#L230) in autocomplete-plus that mentions avoiding a flicker, but I have no idea if it's related.

**Comment by willwhitney** [comment]
Thanks for filing the issue! Next time I run into it I’ll try to document
for them. It’s not showing up when I’m trying to make it happen right now.

I’m pretty sure the autocomplete-plus comment is unrelated — they’re doing
animation in that method, and I think they’re trying to make sure that
nothing has changed before they animate.
